apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-mongo-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-mongo
  template:
    metadata:
      labels:  # ✅ Fixed: Changed from matchLabels to labels
        app: auth-mongo
    spec:
      containers:
        - name: auth-mongo
          image: mongo
          ports:
            - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: auth-mongo-service  # ✅ Changed service name to match auth-mongo
spec:
  selector:
    app: auth-mongo  # ✅ Fixed: Matched the label from Deployment
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP  # ✅ Added for internal cluster communication
